### PR TITLE
Putting Pouch configuration in config/environment makes no sense!!

### PR DESCRIPTION
**Pull request by devinrhode2**
(sarcasm) I like what you did and improved it. I'm also trying to match this with some EmberPouch documentation, because I'm going to link to this repo as an example

also the formatting was a little off at the bottom

Actually I'm going to submit this PR so I don't have to finangle with this message, but I have one more commit, for 3 total.

### CODE REVIEW

**Comment by devinrhode2** [comment]
4 total. Leaving the `config.local_couch || 'bloggr'` to keep things more similar to EmberPouch docs, so it's just a bit easier to learn and less work.

Ready for review.

**Comment by devinrhode2** [comment]
FTR EmberPouch docs that I'm also contributing to, see https://github.com/nolanlawson/ember-pouch/pull/30

**Comment by broerse** [comment]
In production you `local_couch` must sometimes be named differently I think because you must ensure  development data will not spill over to your production CouchDB via your browsers PouchDB.

**Comment by devinrhode2** [comment]
Could you confirm if that's the case? What browsers, DevTools, etc?

**Comment by broerse** [comment]
No I can't. I have seen it happen but that can be with some older Pouch or some browser testing. In production I don't take the risk.

Do you have time to change the installation part in: https://github.com/broerse/ember-cli-blog/blob/master/README.md

**Comment by devinrhode2** [comment]
I don't know what you want me to update

If it's the differently named local couch, while I would do the same, I
don't want to declare this as fact anywhere, it's really not very clear how
this would happen (except if you are editing /etc/hosts)


-Devin <http://zerply.com/DevinRhode2>
<http://zerply.com/devinrhode2>

**Comment by broerse** [comment]
I found some time and updated the readme.

**Pull request merged**
